### ISSUE TITLE
现在直接用路由可以吗？

### ISSUE THREAD

**Issue by Baby-233** [leetking/cwnu-drcom.lua#1]
现在直接用的话   过一段时间会提示禁止使用代理。请问这是咋回事啊。

**Comment by leetking** [comment]
这个程序没法，这只是认证程序，需要在外搭建服务器加密传输会被检测出来的协议，比如 HTTP

**Comment by tourred** [comment]
重庆工商也是web认证上网，直接路由器用一会就会监测出来，然后封禁账号。抓包破解连接算法可以么
@leetking

**Comment by leetking** [comment]
贵校也是 dr.com 认证上网吗？不知道具体情况也不好说。如果和我们学校一样的话，这个没有什么连接算法区别，他是通过流量识别来做的。

**Comment by tourred** [comment]
之前老师用dr.com，学生用的创翼客户端，这学期升级了，改成网页认证登录，开学用路由器连接，用了不到一小时就被监测出来，封号一天，电脑端用wifi分享软件也会被监测然后封号。 @leetking 。

**Comment by Baby-233** [comment]
那就是现在暂时无解咯 @leetking 谢谢咯，麻烦你了

**Comment by leetking** [comment]
@tourred @dujiangchuan 解法就是对可能被识别出行为的流量加密。这个工作目前我也再做，我会把他弄到路由器里，但是用于**解密**和**代理**的服务器需要额外配置。

**Comment by tourred** [comment]
@leetking 谢谢了，那这样全局走代理应该可以绕过检测吧

**Comment by Baby-233** [comment]
@leetking 加密和解密搭建一个ssr就行了嘛，7620系列的路由器刷老毛子登录ssr呗，不过就是服务器好贵啊。

**Comment by leetking** [comment]
@dujiangchuan :cry: 没法呗，只有减少不必要的加密，选择能快速加密或混淆的方法（反正不是为了突破 GFW），这样能提高使用质量

**Comment by Baby-233** [comment]
@leetking 我觉得只有这样最方便，除了vpn和ssr还有什么可以加密啊

**Comment by tourred** [comment]
@leetking 貌似是锐捷搞的，如果分享网络，另外一台设备使用，上传的流量数据里面的mac就会被监测，从而来判断用户是否分享了网络。

**Comment by leetking** [comment]
@dujiangchuan 目前我也是用的ss加密，支持采用了最弱（可能是很快）的加密方法，如果单单只是突破本校检测，比如在数据里按某种方法混入随机字符打乱顺序之类简单的方法也能让他检测不出来，应该需要自行实现，这样方法的运算量应该还要小些（仅为推测）。
@tourred 锐捷不清楚。一般协议都不会把mac上传的，除非是什么私有协议。

**Comment by Baby-233** [comment]
@leetking 这样还是需要购买服务器是吗？

**Comment by leetking** [comment]
@dujiangchuan 目前是这样的，如果有更好的办法最好了

**Comment by Baby-233** [comment]
@leetking 腾讯云有学生机，可以先用来测试一下呗

**Comment by Baby-233** [comment]
@leetking https://wenku.baidu.com/view/8cecec3b783e0912a3162a21.html 阅读一下这个，我们学校应该就是这种的了。感觉真的只能加密才行

**Comment by leetking** [comment]
@dujiangchuan 目前我们就是采用部分流量加密的方法，这几天调试，已经比较稳定了

**Comment by Baby-233** [comment]
@leetking 服务器你用的哪里的，价格怎么样

**Comment by leetking** [comment]
这种私密话题，不在上面讨论。群里说吧，群号码：554344670
