### ISSUE TITLE
路由器不能多人用

### ISSUE THREAD

**Issue by aa92478** [leetking/cwnu-drcom.lua#2]
根据安全策略,禁止共享网络行为,您的网络连接已被限制,请停止共享网络

**Comment by Baby-233** [comment]
哈哈 你也是啊 ，我试过不使用他新装的路由器，直接把进宿舍的主网线插路由器使用，不过还是会被检测，可能是检测一个账号上的mac地址吧。

**Comment by ShunzDai** [comment]
应该不是mac地址吧，win10设置动态mac还是会掉啊

**Comment by leetking** [comment]
学校最新的采用了 深度包检测（DPI）技术，其中只是对明文 HTTP 做了检测，所以对 HTTP 做加密就可以突破了，这里提供的只是认证程序，不提供加密突破的程序，因为加密牵涉到在外面部署服务器。

**Comment by leetking** [comment]
@dujiangchuan 如果你使用了我们的路由器，过段时间把让新程序稳定后就给你换。

**Comment by aa92478** [comment]
使用vpn可以吗

**Comment by leetking** [comment]
@aa92478 那肯定行，但是所有流量都走 VPN 肯定会大幅度降低宽带速度的。
